version: "3.9"
services:
  ros1_simod:
    privileged: true
    build:
      context: .
      dockerfile: ros1_docker/Dockerfile
    environment:
     - DISPLAY=${DISPLAY}
     - NO_AT_BRIDGE=1
     - QT_X11_NO_MITSHM=1
    network_mode: host

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      # Load source folder into target location
      - type: bind
        source: /home/<user_path_to_directory>/simod_docker/ros1_ws
        target: /ros1_ws
    command: 
      /bin/bash -c "cd /ros1_ws && terminator"
# source /opt/ros/noetic/setup.bash
  bridge_simod:
    privileged: true
    build:
      context: .
      dockerfile: bridge_docker/Dockerfile
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    network_mode: host

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev/shm:/dev/shm

      - type: bind
        source: /home/<user_path_to_directory>/simod_docker/bridge_ws
        target: /bridge_ws

    command: 
      /bin/bash -c "cd /bridge_ws && terminator"

  ros2_simod:
    privileged: true
    build:
      context: .
      dockerfile: ros2_docker/Dockerfile
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    network_mode: host

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev/shm:/dev/shm

      - type: bind
        source: /home/<user_path_to_directory>/simod_docker/ros2_ws
        target: /ros2_ws

    command: 
      /bin/bash -c "cd /ros2_ws && terminator"

