# Default initial positions for base's ros2_control fake system

initial_positions:
  right_back_left_wheel_joint: 0
  right_back_right_wheel_joint: 0
  right_front_left_wheel_joint: 0
  right_front_right_wheel_joint: 0