# Default initial positions for dual's ros2_control fake system

initial_positions:
  right_summit_back_left_wheel_joint: 0
  right_summit_back_right_wheel_joint: 0
  right_summit_front_left_wheel_joint: 0
  right_summit_front_right_wheel_joint: 0
  ur_right_elbow_joint: 0
  ur_right_shoulder_lift_joint: 0
  ur_right_shoulder_pan_joint: 0
  ur_right_wrist_1_joint: 0
  ur_right_wrist_2_joint: 0
  ur_right_wrist_3_joint: 0