/**:
  controller_manager:
    ros__parameters:
      update_rate: 500  # Hz
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      ur_right_joint_group_vel_controller:
        type: velocity_controllers/JointGroupVelocityController
        
  joint_state_broadcaster:
    ros__parameters:
      joints:
        - right_summit_back_left_wheel_joint
        - right_summit_back_right_wheel_joint
        - right_summit_front_left_wheel_joint
        - right_summit_front_right_wheel_joint
        - ur_right_shoulder_pan_joint
        - ur_right_shoulder_lift_joint
        - ur_right_elbow_joint
        - ur_right_wrist_1_joint
        - ur_right_wrist_2_joint
        - ur_right_wrist_3_joint

  joint_blw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: $(arg prefix)back_left_wheel_joint
  joint_brw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: $(arg prefix)back_right_wheel_joint
  joint_frw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: $(arg prefix)front_right_wheel_joint
  joint_flw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: $(arg prefix)front_left_wheel_joint


  ur_right_joint_group_vel_controller:
    ros__parameters:
      joints:
        - ur_right_shoulder_pan_joint
        - ur_right_shoulder_lift_joint
        - ur_right_elbow_joint
        - ur_right_wrist_1_joint
        - ur_right_wrist_2_joint
        - ur_right_wrist_3_joint

      pid_gains:
        ur_right_shoulder_pan_joint: {p: 10.0, i: 0.05, d: 0.1}
        ur_right_shoulder_lift_joint: {p: 10.0, i: 0.05, d: 0.1}
        ur_right_elbow_joint: {p: 10.0, i: 0.05, d: 0.1}
        ur_right_wrist_1_joint: {p: 10.0, i: 0.05, d: 0.1}
        ur_right_wrist_2_joint: {p: 10.0, i: 0.05, d: 0.1}
        ur_right_wrist_3_joint: {p: 10.0, i: 0.05, d: 0.1}
      interface_name: velocity  

  robotnik_base_control:
    type: summit_xl_controller/SummitXLController
    joint:
      front_right_wheel_joint:
        name: $(arg prefix)front_right_wheel_joint
        max_speed: 27.27 # rad/s
      front_left_wheel_joint:
        name: $(arg prefix)front_left_wheel_joint
        max_speed: 27.27 # rad/s
      back_right_wheel_joint:
        name: $(arg prefix)back_right_wheel_joint
        max_speed: 27.27 # rad/s
      back_left_wheel_joint:
        name: $(arg prefix)back_left_wheel_joint
        max_speed: 27.27 # rad/s
    linear_speed_limit: 1.5 # m/s
    linear_acceleration_limit: 0.6 # m/s^2
    angular_speed_limit: 3 # rad/s
    angular_acceleration_limit: 1.5 # rad/s^2
    odom_frame: $(arg odom_frame)
    robot_base_frame: $(arg base_frame)
    odom_broadcast_tf: $(arg odom_broadcast_tf)
    odom_topic: 'right_summit/odom'
    wheel_base: $(arg wheel_base)
    track_width: $(arg track_width)
    wheel_diameter: $(arg wheel_diameter)
    cmd_watchdog_duration: 0.5
    imu_watchdog_duration: 0.1
    imu_topic: /right_summit_imu_imu_plugin/out
    odom_publish_frequency: 100
    cmd_vel        : 'right_summit/cmd_vel'
    kinematic_mode : $(arg kinematics)
    motion_odometry: true
    in_motion_timer: 2.0

  joint_read_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100.0

