topics:
  -
    topic: /right_summit/cmd_vel  # Topic name on both ROS 1 and ROS 2
    type: geometry_msgs/msg/Twist  # Type of topic to bridge
    queue_size: 1  # Queue size

  -
    topic: /left_summit/cmd_vel  # Topic name on both ROS 1 and ROS 2
    type: geometry_msgs/msg/Twist  # Type of topic to bridge
    queue_size: 1  # Queue size

  - 
    topic: /right_summit/joint_states  # Topic name on both ROS 1 and ROS 2
    type: sensor_msgs/msg/JointState  # Type of topic to bridge
    queue_size: 1  # Queue size

  - 
    topic: /left_summit/joint_states  # Topic name on both ROS 1 and ROS 2
    type: sensor_msgs/msg/JointState  # Type of topic to bridge
    queue_size: 1  # Queue size

  - 
    topic: /right_summit/robotnik_base_control/odom  # Topic name on both ROS 1 and ROS 2
    type: nav_msgs/msg/Odometry  # Type of topic to bridge
    queue_size: 1  # Queue size
  
  - 
    topic: /left_summit/robotnik_base_control/odom  # Topic name on both ROS 1 and ROS 2
    type: nav_msgs/msg/Odometry  # Type of topic to bridge
    queue_size: 1  # Queue size

  - 
    topic: /right_summit/right_ur_joint_group_pos_controller/command  # Topic name on both ROS 1 and ROS 2
    type: std_msgs/msg/Float64MultiArray  # Type of topic to bridge
    queue_size: 1  # Queue size

  - 
    topic: /left_summit/left_ur_joint_group_pos_controller/command  # Topic name on both ROS 1 and ROS 2
    type: std_msgs/msg/Float64MultiArray  # Type of topic to bridge
    queue_size: 1  # Queue size

  - 
    topic: /gazebo/model_states  # Topic name on both ROS 1 and ROS 2
    type: gazebo_msgs/msg/ModelStates  # Type of topic to bridge
    queue_size: 1  # Queue size


    
    