# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # srm_r_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController


    # srm_l_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController


    srm_r_base_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    srm_r_ur_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    srm_l_base_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    srm_l_ur_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# srm_r_controller:
#   ros__parameters:
#     joints:
#       - right_summit_back_left_wheel_joint
#       - right_summit_back_right_wheel_joint
#       - right_summit_front_left_wheel_joint
#       - right_summit_front_right_wheel_joint
#       - ur_right_shoulder_pan_joint
#       - ur_right_shoulder_lift_joint
#       - ur_right_elbow_joint
#       - ur_right_wrist_1_joint
#       - ur_right_wrist_2_joint
#       - ur_right_wrist_3_joint
#     command_interfaces:
#       []
#     state_interfaces:
#       []
# srm_l_controller:
#   ros__parameters:
#     joints:
#       - left_summit_back_left_wheel_joint
#       - left_summit_back_right_wheel_joint
#       - left_summit_front_left_wheel_joint
#       - left_summit_front_right_wheel_joint
#       - ur_left_shoulder_pan_joint
#       - ur_left_shoulder_lift_joint
#       - ur_left_elbow_joint
#       - ur_left_wrist_1_joint
#       - ur_left_wrist_2_joint
#       - ur_left_wrist_3_joint
#     command_interfaces:
#       []
#     state_interfaces:
#       []
srm_r_base_controller:
  ros__parameters:
    joints:
      - right_summit_back_left_wheel_joint
      - right_summit_back_right_wheel_joint
      - right_summit_front_left_wheel_joint
      - right_summit_front_right_wheel_joint
    command_interfaces:
      []
    state_interfaces:
      []
srm_r_ur_controller:
  ros__parameters:
    joints:
      - ur_right_shoulder_pan_joint
      - ur_right_shoulder_lift_joint
      - ur_right_elbow_joint
      - ur_right_wrist_1_joint
      - ur_right_wrist_2_joint
      - ur_right_wrist_3_joint
    command_interfaces:
      []
    state_interfaces:
      []
srm_l_base_controller:
  ros__parameters:
    joints:
      - left_summit_back_left_wheel_joint
      - left_summit_back_right_wheel_joint
      - left_summit_front_left_wheel_joint
      - left_summit_front_right_wheel_joint
    command_interfaces:
      []
    state_interfaces:
      []
srm_l_ur_controller:
  ros__parameters:
    joints:
      - ur_left_shoulder_pan_joint
      - ur_left_shoulder_lift_joint
      - ur_left_elbow_joint
      - ur_left_wrist_1_joint
      - ur_left_wrist_2_joint
      - ur_left_wrist_3_joint
    command_interfaces:
      []
    state_interfaces:
      []